version: '3'

services:
  postgres:
    image: 'postgres:16.0'
    container_name: my-tg-bot-db
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=tg-bot'
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    build: ./
    container_name: event-service
    ports:
      - "8082:8082"
    environment:
      -  SPRING_DATASOURCE_URL=jdbc:postgresql://my-tg-bot-db:5432/tg-bot?currentSchema=public
      -  SPRING_DATASOURCE_USERNAME=postgres
      -  SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge