package com.example.enums;

import org.springframework.stereotype.Component;


public enum Queues {
    CHECK_IF_REGISTERED_AND_ACTIVATED,
    CHECK_IF_REGISTERED_AND_ACTIVATED_ANSWER,
    REGISTER_USER,
    CHECK_ROLE,
    CHECK_ROLE_ANSWER,
    GET_EVENTS_IN_MY_CITY,
    GET_EVENTS_IN_MY_CITY_ANSWER,
    GET_ALL_EVENTS,
    GET_ALL_EVENTS_ANSWER,
    ADD_EVENT,
    ADD_EVENT_ANSWER,
    CHECK_STATUS,
    CHECK_STATUS_ANSWER,
    SET_STATUS_ADD_EVENT,
    SET_STATUS_BASIC,
    SET_STATUS_REGISTER,
    GET_ALL_ACCEPTED_EVENTS,
    GET_ALL_ACCEPTED_EVENTS_ANSWER,
    ADD_SUGGESTED_EVENT,
    GET_ALL_SUGGESTED_EVENTS,
    SET_STATUS_APPROVE_EVENT_STATE,
    ACCEPT_OR_REJECT_EVENT,
    SET_CITY,
    SET_STATUS_MODIFY_EVENT_STATE,
    SET_STATUS_MODIFY_NAME_STATE,
    GET_USERNAME,
    GET_USERNAME_ANSWER,
    SET_NAME,
    SET_NAME_ANSWER,
    GET_ALL_EVENTS_BY_ID,
    GET_ALL_EVENTS_BY_ID_ANSWER,
    GET_MY_EVENTS_ID,
    GET_MY_EVENTS_ID_ANSWER,
    SET_STATUS_ADD_MY_EVENT,
    SET_STATUS_ADD_MY_EVENT_ANSWER,
    ADD_MY_EVENT,
    ADD_MY_EVENT_ANSWER

}
