package com.example.event.enums;


public enum Queues {
    CHECK_IF_REGISTERED_AND_ACTIVATED,
    CHECK_IF_REGISTERED_AND_ACTIVATED_ANSWER,
    REGISTER_USER,
    CHECK_ROLE,
    CHECK_ROLE_ANSWER,
    GET_EVENTS_IN_MY_CITY,
    GET_EVENTS_IN_MY_CITY_ANSWER,
    GET_ALL_EVENTS,
    GET_ALL_EVENTS_ANSWER,
    GET_ALL_ACCEPTED_EVENTS,
    GET_ALL_ACCEPTED_EVENTS_ANSWER,
    ACCEPT_OR_REJECT_EVENT_ANSWER,
    GET_ALL_EVENTS_BY_ID_ANSWER,
    SEND_EVENT_ID

}
